name: Check version bumped for frontend
on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-*.yml"

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
        with:
          service_name: frontend

      - name: Compare versions
        run: |
          git fetch origin main
          OLD_VERSION=$( (git show origin/main:package.json 2>/dev/null || true) | jq -r '.version' 2>/dev/null || true )
          NEW_VERSION=${{ steps.get-version.outputs.version }}

          echo "OLD_VERSION=$OLD_VERSION"
          echo "NEW_VERSION=$NEW_VERSION"

          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "❌ You must bump version in package.json file for this PR"
            exit 1
          fi

          echo "✅ Version bumped."
