name: Check version bumped for Node Lambdas
on:
  pull_request:
    branches:
      - main
    paths:
      - "lambda/node/**"
      - ".github/workflows/lambda-node-*.yml"
      - ".github/actions/get-version/**"

jobs:
  check-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda/node

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
        with:
          service_name: lambda-node

      - name: Compare versions
        run: |
          git fetch origin main
          OLD_VERSION=$(git show origin/main:lambda/node/package.json | jq -r '.version' 2>/dev/null)
          NEW_VERSION=${{ steps.get-version.outputs.version }}

          echo "OLD_VERSION=$OLD_VERSION"
          echo "NEW_VERSION=$NEW_VERSION"

          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "❌ You must bump version in package.json for this PR"
            exit 1
          fi
          
          echo "✅ Version bumped."
