name: Deploy igdb-enricher Lambda to AWS

on:
  push:
    branches:
      - main
    paths:
      - "lambda/python/**"
      - ".github/workflows/lambda-python-*.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda/python

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
        with:
          service_name: lambda-python

      - name: Build lambda package
        uses: ./.github/actions/build-python-lambda
        with:
          zip_path: lambda.zip

      - name: Deploy to AWS
        uses: ./.github/actions/deploy-lambda
        with:
          function_name: trophyquest-igdb-enricher
          semantic_version: ${{ steps.get-version.outputs.version }}
          zip_path: lambda.zip
          aws_region: ${{ secrets.AWS_REGION }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}