name: Deploy psn-fetcher Lambda to AWS

on:
  push:
    branches:
      - main
    paths:
      - "lambda/node/**"
      - ".github/workflows/lambda-node-deploy-fetcher.yml"
      - ".github/actions/get-version/action.yml"
      - ".github/actions/package-lambda/action.yml"
      - ".github/actions/deploy-lambda/action.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda/node

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: lambda/node/package-lock.json

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
        with:
          service_name: lambda-node

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prune dev deps
        run: npm prune --production

      - name: Package Lambda
        uses: ./.github/actions/package-lambda
        with:
          zip_path: lambda.zip
          lambda_type: node

      - name: Deploy to AWS
        uses: ./.github/actions/deploy-lambda
        with:
          function_name: trophyquest-psn-fetcher
          semantic_version: ${{ steps.get-version.outputs.version }}
          alias_name: prod
          zip_path: lambda.zip
          aws_region: ${{ secrets.AWS_REGION }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}